### ISSUE TITLE
Website Does Not Work With Stats v3.

### ISSUE THREAD

**Issue by GiuseppeGroth** [DevelopGravity/Fluid-MC-Stats#47]
I get this error on the top players page
These are users with current top rankings on the server.
![statssql](https://cloud.githubusercontent.com/assets/1659170/9024277/85529f48-38c6-11e5-8ab0-6e16bedf02f3.PNG)
Table 'mc_stats.stats_player' doesn't exist

plugin mysql

``` yaml
# Only use this file if you've set "storage" to "mysql" in config.yml
# Otherwise this file will be ignored.

host: localhost
port: 3306
user: mc_stats
pass: *****
database: mc_stats
prefix: stats_
```

webweite conf

``` php
<?php
/**
 * Copyright (c) AccountProductions and Sybren Gjaltema, 2014. All rights reserved.
 */

/**
 * MySQL
 */
$mysql_host = "localhost";
$mysql_database = "mc_stats";
$mysql_port = "3306";
$mysql_user = "mc_stats";
$mysql_pwd = "*****";
$mysql_table_prefix = "stats_";
```

```
Edited by @ZacharyDuBois to be properly formatted in markdown.
```
